{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ai-control-plane.fullname" . }}
  labels:
    {{- include "ai-control-plane.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "ai-control-plane.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: http
          protocol: TCP
      {{- with .Values.networkPolicy.extraIngress }}
      from:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
